### ISSUE TITLE
Compare goccy/go-json to minio/simdjson-go for performance

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#170]
Currently for json parsing goccy/go-json is being used, We should research if using minio/simdjson-go provides performance gains.

We might also choose to simply go ahead and start using latest graviton instances (c7g) on aws without any code change to see if it offers better price /performance.

**Comment by DavexPro** [comment]
Maybe you can try [bytedance/sonic](https://github.com/bytedance/sonic), it could be a good choice.

**Comment by hengfeiyang** [comment]
As my test with zinc

test document:

```
{"Year": 1896, "City": "Athens", "Sport": "Aquatics", "Discipline": "Swimming", "Athlete": "HAJOS, Alfred", "Country": "HUN", "Gender": "Men", "Event": "100M Freestyle", "Medal": "Gold", "Season": "summer"}
```

test request:

```
hey -c 10 -z 10s -H "Authorization: Basic YWRtaW46Q29tcGxleHBhc3MjMTIz" -m POST -d '{"Year": 1896, "City": "Athens", "Sport": "Aquatics", "Discipline": "Swimming", "Athlete": "HAJOS, Alfred", "Country": "HUN", "Gender": "Men", "Event": "100M Freestyle", "Medal": "Gold", "Season": "summer"}' http://localhost:4080/api/myindex/_doc
```

result with go-json:
```
Summary:
  Total:	10.0003 secs
  Slowest:	0.0607 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	57163.8727
```

```
Summary:
  Total:	10.0002 secs
  Slowest:	0.1128 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	57853.6767
```

```
Summary:
  Total:	10.0020 secs
  Slowest:	0.0947 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	57519.5033
```

result with sonic:

```
Summary:
  Total:	10.0002 secs
  Slowest:	0.0942 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	63122.7861
```

```
Summary:
  Total:	10.0002 secs
  Slowest:	0.1041 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	63383.6638
```

```
Summary:
  Total:	10.0003 secs
  Slowest:	0.0917 secs
  Fastest:	0.0000 secs
  Average:	0.0002 secs
  Requests/sec:	62942.0047
```

| library | time 1 | time 2 | time 3 | avg |  base |
|--------|------|--------|-------|-----|----------|
| go-json | 57163 | 57853 | 57519 |  57511     | 100.00%  |
| sonic   | 63122 | 63383 | 62942 |   63149    | 109.80% |

It looks sonic have 10% increased.
