### ISSUE TITLE
integrate with filebeat

### ISSUE THREAD

**Issue by gorsing** [zinclabs/zinc#25]
Good afternoon. Are there any plans to integrate with filebeat?

**Comment by fossxplorer** [comment]
I tried to setup Filebeat to forward logs directly to Zinc, but has been unable so far.
I see the following error using both Filebeat and Journalbeat:
```
[root@lb01 ~]# filebeat test config
Config OK
[root@lb01 ~]# filebeat test output
elasticsearch: http://zinchost.localdomain:4080...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 10.0.2.50
    dial up... OK
  TLS... WARN secure connection disabled
  talk to server... ERROR Failed to parse JSON response: invalid character '<' looking for beginning of value
```

Here is the relevant part of Filebeat (output):
```
 output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["zinchost.localdomain:4080"]
  username: "admin"
  password: "secret"
```
However, i have been able to forward logs to Zinc using Fluent Bit.

**Comment by susinths** [comment]
I tried to setup Filebeat to forward logs directly to Zinc, but has been unable so far.
I see the following error using both Filebeat and Journalbeat:
```
[root@lb01 ~]# filebeat test config
Config OK
[root@lb01 ~]# filebeat test output
elasticsearch: http://zinchost.localdomain:4080...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 10.0.2.50
    dial up... OK
  TLS... WARN secure connection disabled
  talk to server... ERROR Failed to parse JSON response: invalid character '<' looking for beginning of value
```

Here is the relevant part of Filebeat (output):
```
 output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["zinchost.localdomain:4080"]
  username: "admin"
  password: "secret"
```
However, i have been able to forward logs to Zinc using Fluent Bit.
