### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by yxw21** [zinclabs/zinc#492]
Yesterday I added data for index so that it could be retrieved normally. 
But when I tried to retrieve the data again today, I found that there was no data available.

I used S3 storage for the index named test. 
And S3 data still exists.

I used the zinc binaries to build an image (mv zinc zinc_linux_amd64)
```
FROM alpine
WORKDIR /app
COPY zinc_linux_amd64 ./
RUN apk add ca-certificates &&\
    chmod +x ./zinc_linux_amd64
EXPOSE 4080
ENTRYPOINT [ "./zinc_linux_amd64" ]
```
Then use the following file to deploy zinc to my K8s cluster
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zinc
spec:
  nfs:
    path: xxxxx
    server: xxxxx
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zinc-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zinc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zinc
  template:
    metadata:
      labels:
        app: zinc
    spec:
      automountServiceAccountToken: false
      containers:
        - name: zinc
          image: aws.ecr/zinc:latest
          imagePullPolicy: Always
          env:
            - name: ZINC_S3_BUCKET
              value: xxxxx
            - name: AWS_CONFIG_FILE
              value: /s3/config
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /s3/credentials
            - name: ZINC_FIRST_ADMIN_USER
              value: admin
            - name: ZINC_FIRST_ADMIN_PASSWORD
              value: 123456
            - name: ZINC_DATA_PATH
              value: /data/zinc
          resources:
            limits:
              cpu: 1024m
              memory: 2048Mi
            requests:
              cpu: 32m
              memory: 50Mi
          ports:
            - containerPort: 4080
              name: http
          volumeMounts:
            - name: zinc-pvc
              mountPath: /data/zinc
            - name: s3
              mountPath: /s3
      volumes:
        - name: zinc-pvc
          persistentVolumeClaim:
            claimName: zinc-pvc
        - name: s3
          configMap:
            name: s3

---

apiVersion: v1
kind: Service
metadata:
  name: zinc-service
spec:
  selector:
    app: zinc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4080
```

**What version of ZincSearch are you using?**

v0.3.0

**Any attachments/screenshots?**

## Index data is normal.
<img width="1655" alt="1" src="https://user-images.githubusercontent.com/16237562/187611972-b687a4d7-cee6-4c04-95d0-33fe2bff9617.png">

## No data available
<img width="700" alt="2" src="https://user-images.githubusercontent.com/16237562/187611977-cabb898b-ffe2-4975-abc1-a22c4826ae54.png">

## Disk file exists
<img width="580" alt="3" src="https://user-images.githubusercontent.com/16237562/187611982-2dfee1d0-5399-4708-b8b9-3bb80e86a4e1.png">
