### ISSUE TITLE
Docker compose not working like expected on MacOS

### ISSUE THREAD

**Issue by alexander-schranz** [zinclabs/zinc#710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

Hello, I'm trying to get a zincsearch server starting via docker compose on MacOS;

```yml
services:
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
    ports:
      - "4080:4080"
    volumes:
      - zinc-data:/data

volumes:
  zinc-data:
```

**What action did you take?**

```bash
docker compose up
```

**What action/response/output did you expect?**

That the docker container starts:

**What actually happened?**

> seal-zinc-adapter-zinc-1  | {"level":"debug","time":"2023-01-15T19:00:14Z","message":"open .env: no such file or directory"}
> seal-zinc-adapter-zinc-1  | {"level":"fatal","error":"mkdir data/_test_: no space left on device","time":"2023-01-15T19:00:14Z","message":"ZINC_DATA_PATH is not writable"}

As there is no way to run `chmod a+rwx ./data` like mention in the docs. It sounds for me there is something wrong with the image that it does not work like expected.

**How to reproduce the issue?**

Use the docker compose file above and try to run `docker compose up`.

**What version of ZincSearch are you using?**

Did try `:latest` and `0.3.6`.

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

There is enough space available and no other docker images ever did run into similar issues. So for me it looks like the permissions already false set by the created docker image?

Related Windows Docker issue #454 

**Any attachments/screenshots?**

<img width="824" alt="Bildschirmfoto 2023-01-15 um 20 08 08" src="https://user-images.githubusercontent.com/1698337/212561808-a0f2887a-5f09-4564-ab2e-d317ae400a98.png">

**Which service(s) is this relate to?**

Docker Image
